import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { beforeEach, describe, expect, it, vi } from 'vitest';

import { ApiError } from '@/lib/api';
import { MIN_SECTION_CHARS, type BoardReport, type PersonaSummary } from '@/lib/grants';
import { setAccessToken } from '@/lib/session';

import { ReviewBoard } from './ReviewBoard';

const reviewPersonas = vi.fn();
const reviewSection = vi.fn();

vi.mock('@/lib/api', async () => {
  const actual = await vi.importActual<typeof import('@/lib/api')>('@/lib/api');
  return {
    ...actual,
    api: {
      reviewPersonas: (...args: unknown[]) => reviewPersonas(...args),
      reviewSection: (...args: unknown[]) => reviewSection(...args),
    },
  };
});

const PERSONAS: PersonaSummary[] = [
  {
    id: 'strict_biostatistician',
    name: 'Strict Biostatistician',
    focus: 'Sample size and statistical power',
    criteria: ['Statistical Power and Sample Size', 'Analysis Plan and Rigor'],
  },
  {
    id: 'commercialization_critic',
    name: 'Industry Commercialization Critic',
    focus: 'Market viability',
    criteria: ['Market Viability'],
  },
];

function report(overrides: Partial<BoardReport> = {}): BoardReport {
  return {
    section_name: 'Research Strategy',
    program: 'SBIR',
    phase: 'Phase I',
    config_version: '2026.08-1',
    validation_status: 'unvalidated',
    caveat:
      'These scores were generated by a language model role-playing reviewer personas. They are not calibrated against real NIH or SBIR reviewer scores.',
    model: 'claude-sonnet-4-5',
    summary: 'Two personas reviewed the section; the weakest score was 7 on sample size.',
    reviews: [
      {
        persona_id: 'strict_biostatistician',
        persona_name: 'Strict Biostatistician',
        focus: 'Sample size and statistical power',
        scores: [
          {
            criterion: 'Statistical Power and Sample Size',
            score: 7,
            reasoning: 'No effect size or alpha is stated for the power calculation.',
          },
        ],
        overall_score: 7,
        strengths: ['The primary endpoint is pre-specified.'],
        weaknesses: ['Sample size is asserted rather than justified.'],
        comment: 'The design is judgeable but the quantification is not there yet.',
      },
    ],
    ...overrides,
  };
}

const DRAFT = 'a'.repeat(MIN_SECTION_CHARS + 10);

beforeEach(() => {
  setAccessToken('token-123');
  reviewPersonas.mockReset();
  reviewSection.mockReset();
  reviewPersonas.mockResolvedValue(PERSONAS);
  reviewSection.mockResolvedValue(report());
});

describe('mock review board', () => {
  it('carries the unvalidated caveat before any draft is submitted', async () => {
    render(<ReviewBoard />);

    expect(screen.getByRole('note')).toHaveTextContent(
      /Unvalidated mock review.*not calibrated against real NIH or SBIR reviewer scores/is,
    );
    expect(screen.getByText('No review run yet')).toBeInTheDocument();
    expect(await screen.findByText(/Strict Biostatistician/)).toBeInTheDocument();
  });

  it('will not submit a section too short for a persona to review', async () => {
    const user = userEvent.setup();
    render(<ReviewBoard />);

    expect(screen.getByRole('button', { name: 'Run the board' })).toBeDisabled();

    await user.type(screen.getByLabelText('Draft section text'), DRAFT);
    expect(screen.getByRole('button', { name: 'Run the board' })).toBeEnabled();
    expect(reviewSection).not.toHaveBeenCalled();
  });

  it('sends the picked personas and renders each critique on the NIH scale', async () => {
    const user = userEvent.setup();
    render(<ReviewBoard />);

    await screen.findByText(/Strict Biostatistician/);
    await user.click(screen.getByRole('checkbox', { name: /Strict Biostatistician/ }));
    await user.type(screen.getByLabelText('Draft section text'), DRAFT);
    await user.click(screen.getByRole('button', { name: 'Run the board' }));

    await waitFor(() => expect(reviewSection).toHaveBeenCalledTimes(1));
    expect(reviewSection.mock.calls[0][0]).toMatchObject({
      section_name: 'Research Strategy',
      program: 'SBIR',
      phase: 'Phase I',
      personas: ['strict_biostatistician'],
    });

    expect(await screen.findByText('7.0 / 9 overall')).toBeInTheDocument();
    expect(screen.getByText('Statistical Power and Sample Size')).toBeInTheDocument();
    expect(
      screen.getByText('No effect size or alpha is stated for the power calculation.'),
    ).toBeInTheDocument();
    expect(screen.getByText('Sample size is asserted rather than justified.')).toBeInTheDocument();
    // The report's own caveat travels with the scores, not just the standing band.
    expect(
      screen.getByText(/These scores were generated by a language model role-playing/),
    ).toBeInTheDocument();
    expect(screen.getByText(/claude-sonnet-4-5 · personas 2026.08-1 · unvalidated/)).toBeInTheDocument();
  });

  it('shows no scores at all when no model is configured', async () => {
    const user = userEvent.setup();
    reviewSection.mockRejectedValue(
      new ApiError('the review board needs an LLM API key; no score is produced without one', 503),
    );
    render(<ReviewBoard />);

    await user.type(screen.getByLabelText('Draft section text'), DRAFT);
    await user.click(screen.getByRole('button', { name: 'Run the board' }));

    expect(await screen.findByRole('alert')).toHaveTextContent(
      'the review board needs an LLM API key',
    );
    expect(screen.getByText('No review run yet')).toBeInTheDocument();
  });

  it('says a refused review produced no scores', async () => {
    const user = userEvent.setup();
    reviewSection.mockRejectedValue(
      new ApiError('Strict Biostatistician returned an empty reply.', 502),
    );
    render(<ReviewBoard />);

    await user.type(screen.getByLabelText('Draft section text'), DRAFT);
    await user.click(screen.getByRole('button', { name: 'Run the board' }));

    expect(await screen.findByRole('alert')).toHaveTextContent('No scores were produced.');
    expect(screen.getByText('No review run yet')).toBeInTheDocument();
  });

  it('asks the reader to sign in again rather than echoing an auth failure', async () => {
    const user = userEvent.setup();
    reviewSection.mockRejectedValue(new ApiError('Not authenticated', 401));
    render(<ReviewBoard />);

    await user.type(screen.getByLabelText('Draft section text'), DRAFT);
    await user.click(screen.getByRole('button', { name: 'Run the board' }));

    expect(await screen.findByRole('alert')).toHaveTextContent(
      'Your session has expired. Sign in again to run a review.',
    );
  });

  it('does not surface a network failure as a raw exception', async () => {
    const user = userEvent.setup();
    reviewSection.mockRejectedValue(new TypeError('Failed to fetch'));
    render(<ReviewBoard />);

    await user.type(screen.getByLabelText('Draft section text'), DRAFT);
    await user.click(screen.getByRole('button', { name: 'Run the board' }));

    expect(await screen.findByRole('alert')).toHaveTextContent(
      'The review board could not be reached. Check your connection and try again.',
    );
  });

  it('says the personas could not be loaded rather than showing an empty board', async () => {
    reviewPersonas.mockRejectedValue(new ApiError('personas are unusable', 500));
    render(<ReviewBoard />);

    expect(await screen.findByRole('alert')).toHaveTextContent(
      'Reviewer personas could not be loaded: personas are unusable',
    );
  });
});
