"""
A drafter that writes deliberately wrong numbers, so the audit path can be exercised on demand.

This exists because the auditor's flags are unreachable through the running app on purpose: the
model is asked to copy the record verbatim, and when it complies — which it does — the audit
finds nothing and the flagged view never renders. That leaves the most safety-relevant screen in
the tab reviewable only through unit tests. This drafter closes that gap by producing a narrative
built from the submitted table with known corruptions injected, so the flags, their severities and
their context quotes can be seen end to end.

It is not a model and must never be mistaken for one:

* it is only selectable when `regulatory_fixture_drafter` is set, which `Settings` refuses
  outside the development environment;
* the report it produces carries `fixture_draft=True` and `drafter="fixture-contradiction"`,
  which the UI renders as a warning band above the narrative; and
* every section states in its own `gaps` that the text is fixture output with corrupted numbers.

The corruptions are derived from the submitted table rather than hardcoded, so any study record
produces flags: a named study-level value is restated with a doubled magnitude (a critical
`contradicted_value`), and a computed number that appears nowhere in the record is added (an
`unsupported_number`). Nothing here is regulatory content, and nothing here should be read as an
example of how a narrative should be written.
"""

from __future__ import annotations

from decimal import Decimal

from .audit import collect_source_values
from .drafter import DraftedSection
from .models import SectionKey, StudyTable

FIXTURE_DRAFTER_NAME = "fixture-contradiction"

FIXTURE_GAP = (
    "Fixture output, not a drafted narrative: this text was generated by a test fixture and "
    "contains deliberately corrupted numbers to exercise the numeric audit."
)


def _unused_integer(table: StudyTable) -> Decimal:
    """An integer the study table does not contain, so it is flagged as unsupported."""
    taken = {source.value for source in collect_source_values(table)}
    candidate = Decimal(137)
    while candidate in taken:
        candidate += 1
    return candidate


def _contradiction(table: StudyTable) -> str:
    """
    Restate one of the table's own numbers with the wrong magnitude.

    A named study-level value is preferred because that is the critical case — a claim attached
    to the name of a value the table defines differently. Failing that, a dose is doubled, which
    the auditor reaches as a number it cannot trace to the record.
    """
    for measurement in table.measurements:
        if measurement.quantity is not None:
            wrong = measurement.quantity.value * 2
            unit = measurement.quantity.unit
            return f"The {measurement.name} was {wrong} {unit}.".replace("  ", " ")
        if measurement.text_value.strip():
            return f"The {measurement.name} was {_unused_integer(table)} mg/kg/day."
    for group in table.groups:
        if group.dose is not None:
            wrong = group.dose.value * 2
            return f"Animals in {group.label} received {wrong} {group.dose.unit}.".replace(
                "  ", " "
            )
    for finding in table.findings:
        if finding.quantity is not None:
            wrong = finding.quantity.value * 2
            return f"{finding.endpoint} was {wrong} {finding.quantity.unit}.".replace("  ", " ")
    return f"A dose of {_unused_integer(table)} mg/kg/day was administered."


def _design_text(table: StudyTable) -> str:
    parts = [f"Study {table.study_id} was conducted"]
    if table.species:
        parts.append(f"in the {table.species}")
    if table.route:
        parts.append(f"by the {table.route} route")
    if table.duration:
        parts.append(f"for {table.duration}")
    opening = " ".join(parts) + "."
    groups = "; ".join(
        f"{group.label} at {group.dose.render()}" if group.dose else group.label
        for group in table.groups
    )
    if groups:
        opening += f" Dose groups were: {groups}."
    return opening + " " + _contradiction(table)


def _results_text(table: StudyTable) -> str:
    lines = []
    for finding in table.findings:
        rendered = finding.quantity.render() if finding.quantity else ""
        incidence = finding.incidence.render() if finding.incidence else ""
        detail = ", ".join(part for part in (rendered, incidence, finding.severity) if part)
        lines.append(f"{finding.endpoint}{f' ({detail})' if detail else ''}")
    body = (
        "The following were observed: " + "; ".join(lines) + "."
        if lines
        else "No findings were submitted for this study."
    )
    unsupported = _unused_integer(table)
    return (
        f"{body} Body weight gain in treated animals was {unsupported}% of control, and the "
        "difference was considered treatment related."
    )


def _interpretation_text(table: StudyTable) -> str:
    stated = "; ".join(
        f"{measurement.name}: {measurement.render()}"
        for measurement in table.measurements
        if measurement.render()
    )
    opening = (
        f"Study-level values submitted for this study were: {stated}."
        if stated
        else "No study-level values were submitted for this study."
    )
    return (
        f"{opening} Interpretation of these findings, and any conclusion about a starting dose, "
        "is left to the reviewing regulatory affairs professional."
    )


class FixtureNarrativeDrafter:
    """Deterministic corrupt-narrative generator. Development only; see the module docstring."""

    name = FIXTURE_DRAFTER_NAME

    async def draft(self, table: StudyTable) -> list[DraftedSection]:
        return [
            DraftedSection(
                key=SectionKey.STUDY_DESIGN, text=_design_text(table), gaps=[FIXTURE_GAP]
            ),
            DraftedSection(key=SectionKey.RESULTS, text=_results_text(table), gaps=[FIXTURE_GAP]),
            DraftedSection(
                key=SectionKey.INTERPRETATION, text=_interpretation_text(table), gaps=[FIXTURE_GAP]
            ),
        ]


__all__ = ["FIXTURE_DRAFTER_NAME", "FIXTURE_GAP", "FixtureNarrativeDrafter"]
