from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

# The NIH scale, kept as the model's own numbers: 1 is exceptional and 9 is poor, so a lower
# overall score is a better review. Nothing here rescales it into a percentage.
MIN_SCORE = 1
MAX_SCORE = 9

MIN_TEXT_CHARS = 200
MAX_TEXT_CHARS = 20_000

VALIDATION_STATUS: Literal["unvalidated"] = "unvalidated"
CAVEAT = (
    "These scores were generated by a language model role-playing reviewer personas. They are "
    "not calibrated against real NIH or SBIR reviewer scores, carry no predictive value for a "
    "funding decision, and require review by a qualified human reviewer before being acted on."
)


class ProposalSection(BaseModel):
    """
    The draft text to be reviewed, plus what the writer says it is.

    `program` and `phase` are free text rather than enums: they are context handed to the
    personas, not facts the board decides anything on, and a section can be written for a
    solicitation this codebase has no enum for.
    """

    section_name: str = Field(min_length=1, max_length=200)
    program: str = Field(default="", max_length=100)
    phase: str = Field(default="", max_length=100)
    text: str = Field(min_length=MIN_TEXT_CHARS, max_length=MAX_TEXT_CHARS)


class CriterionScore(BaseModel):
    """One criterion's score on the NIH 1-9 scale, with the reasoning the persona gave for it."""

    criterion: str
    score: int = Field(ge=MIN_SCORE, le=MAX_SCORE)
    reasoning: str = ""


class PersonaReview(BaseModel):
    """
    One persona's review of the section.

    `overall_score` is the mean of the criterion scores that survived validation, not a number
    the model reported separately: a persona whose criterion scores and overall disagree would
    otherwise present arithmetic that cannot be checked against the table above it.
    """

    persona_id: str
    persona_name: str
    focus: str = ""
    scores: list[CriterionScore] = Field(default_factory=list)
    overall_score: float = Field(ge=MIN_SCORE, le=MAX_SCORE)
    strengths: list[str] = Field(default_factory=list)
    weaknesses: list[str] = Field(default_factory=list)
    comment: str = ""


class BoardReport(BaseModel):
    """
    Every persona's review of one section, with the caveat that travels with it.

    `validation_status` and `caveat` are fields rather than documentation because this payload
    is what a client renders: a consumer cannot read the docstring, and a score shown without
    the caveat reads as a real study-section score, which it is not.
    """

    section_name: str
    program: str | None = None
    phase: str | None = None
    config_version: str = ""
    validation_status: Literal["unvalidated"] = VALIDATION_STATUS
    caveat: str = CAVEAT
    model: str = ""
    reviews: list[PersonaReview] = Field(default_factory=list)
    summary: str = ""


class PersonaSummary(BaseModel):
    """A persona as shown to a client choosing a board. The system prompt is deliberately absent."""

    id: str
    name: str
    focus: str = ""
    criteria: list[str] = Field(default_factory=list)
